config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :searches
  resources :review_users
  resources :review_lodgings
  resources :reservations
  resources :reports
  resources :messages
  resources :users
  resources :lodgings

  resources :users do
    resources :lodgings, shallow: true
  end
  resources :users do
    resources :reservations, shallow: true
  end
  resources :users do
    resources :review_users, shallow: true
  end
  resources :users do
    resources :review_lodgings, shallow: true
  end
  resources :users do
    resources :messages, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :lodgings
      end
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lodgings
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  validates :email, email: true, uniqueness: true, presence: true
  has_many :lodgings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :review_users_received, class_name: 'ReviewUser', foreign_key: 'received_id' , dependent: :destroy
  has_many :review_users_made, class_name: 'ReviewUser', foreign_key: 'made_id' , dependent: :destroy
  has_many :inbox_as_messageSender, class_name: 'Message', foreign_key: 'messageSender_id' , dependent: :destroy
  has_many :inbox_as_messageReceiver, class_name: 'Message', foreign_key: 'messageReceiver_id' , dependent: :destroy
  has_many :sended_reports, class_name: 'Report', foreign_key: 'reportSender_id' , dependent: :destroy
  has_many :received_reports, class_name: 'Report', foreign_key: 'reportReceiver_id' , dependent: :destroy


  accepts_nested_attributes_for :lodgings, allow_destroy: true
  accepts_nested_attributes_for :reservations, allow_destroy: true
  accepts_nested_attributes_for :review_users_received, allow_destroy: true
  accepts_nested_attributes_for :review_users_made, allow_destroy: true
  accepts_nested_attributes_for :inbox_as_messageSender, allow_destroy: true
  accepts_nested_attributes_for :inbox_as_messageReceiver, allow_destroy: true
  accepts_nested_attributes_for :sended_reports, allow_destroy: true
  accepts_nested_attributes_for :received_reports, allow_destroy: true


end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < APIController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /api/v1/users
  def index
    @users = User.includes(:lodgings).all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      render :show, status: :created, location: api_v1_users_path(@user)
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      render :show, status: :ok, location: api_v1_users_path(@user)
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    redirect_to api_v1_users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {}).
      permit(:id, :email, :first_name, :last_name, :rut, :password,
             { lodgings_attributes: [:id, :name,:availability_from,
                                     :availability_to, :description, :daily_fee, :location,
                                     :pets_accepted, :parking_lot, :breakfast_included,
                                     :single_bed, :double_bed, :rooms, :bathrooms, :jacuzzi,
                                     :gym, :smoke_free],
               reservations_attributes: [:id, :entry_date, :departure_date, :price, :transfer_receipt,
                                         :reserve_expiration, :lodging_id],
               review_users_received_attributes: [:id, :text, :rating, :is_a_guest, :made_id],
               review_users_made_attributes: [:id, :text, :rating, :is_a_guest, :received_id],
               inbox_as_messageSender_attributes: [:id, :text, :messageReceiver_id],
               inbox_as_messageReceiver_attributes: [:id, :text, :messageSender_id],
               sended_reports_attributes: [:id, :subject, :text, :file, :reportReceiver_id],
               received_reports_attributes: [:id, :subject, :text, :file, :reportSender_id]
             })
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb:

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
         user = User.create(name: data['name'],
                            email: data['email'],
                            password: Devise.friendly_token[0,20]
         )
    end
    user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.where(["email LIKE ?","%#{params[:search]}%"]).or(User.where(["first_name LIKE ?","%#{params[:search]}%"]))or(User.where(["last_name LIKE ?","%#{params[:search]}%"])).or(User.where(["location LIKE ?","%#{params[:search]}%"]))
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.with(user: @user).welcome_email.deliver_now


        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :rut, :password, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div style="margin: 3rem">
  <%= form_with(model: user) do |form| %>

    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :rut %>
      <%= form.text_field :rut %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>


</div>

app/views/users/edit.html.erb
<div style="margin: 3rem">
  <div style="margin: 3rem">
    <h1>Editing User</h1>
    <span>
      <%= link_to 'Show', @user, class: "btn btn-outline-dark align-content-center float-end"%>
      <%= link_to 'Back', users_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>
   </span>
  </div>


  <%= render 'form',  user: @user %>


</div>

app/views/users/index.html.erb
<div style="margin: 3rem">

  <h1>Users</h1>

  <%= form_tag users_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <%end %> <br />

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @users.each do |user| %>
          <div class="col">
            <div class="card shadow-sm">
              <div class="card-body">
                <a class="card-title"><%= user.email %></a>
                <p class="card-text" style="height: 30px" ><%=user.first_name %> <%=user.last_name %>  Rut: <%=user.rut %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to 'View', user, class: "btn btn-sm btn-outline-secondary" %>
                    <%if can? :manage, :user %>
                      <%= link_to 'Edit', edit_user_path(user), class: "btn btn-sm btn-outline-secondary" %>
                      <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" %>

                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <% end %>
      </div>

    </div>
  </div>


  <div class="d-grid gap-2">
    <%= link_to 'New User', new_user_path, class: "btn btn-outline-dark btn-lg btn-block"%>
  </div>



</div>

app/views/users/new.html.erb
<div style="margin: 3rem">
  <div style="margin: 3rem">
    <h1>New User</h1>

    <span>
     <%= link_to 'Back', users_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>
    </span>
  </div>


  <%= render 'form', user: @user %>

</div>

app/views/users/show.html.erb
<div style="margin: 3rem">

  <div style="margin: 3rem">
    <p><h3><strong><%= @user.first_name %>&nbsp;<%= @user.last_name %></strong></h3>
    <span>
      <%unless !user_signed_in?%>
        <% session[:watch_list] ||= "[]" %>
        <%session[:watch_list] = ActiveSupport::JSON.decode(session[:watch_list])%>
        <%session[:watch_list].push( @user.id )%>
        <%session[:watch_list] = ActiveSupport::JSON.encode(session[:watch_list])%>

        <%= link_to 'Contact', new_user_message_path(@user.id), class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 15px"%>
      <%end %>
     <%= link_to 'Back', users_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>
    </span>
  </div>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @user.rut %>
</p>

</div>