config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :searches
  resources :review_users
  resources :review_lodgings
  resources :reservations
  resources :reports
  resources :messages
  resources :users
  resources :lodgings

  resources :users do
    resources :lodgings, shallow: true
  end
  resources :users do
    resources :reservations, shallow: true
  end
  resources :users do
    resources :review_users, shallow: true
  end
  resources :users do
    resources :review_lodgings, shallow: true
  end
  resources :users do
    resources :messages, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :lodgings
      end
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lodgings
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

end

app/models/search.rb
class Search < ApplicationRecord

  def search_lodgings

    lodgings = Lodging.all
    lodgings = lodgings.where(['name LIKE ?', "%#{keywords}"]) if keywords.present?
    lodgings = lodgings.where(['availability_from <= ?', check_in]) if check_in.present?
    lodgings = lodgings.where(['availability_to >= ?', check_out]) if check_out.present?
    lodgings = lodgings.where(['daily_fee >= ?', daily_fee_min]) if daily_fee_min.present?
    lodgings = lodgings.where(['daily_fee <= ?', daily_fee_max]) if daily_fee_max.present?
    lodgings = lodgings.where(['location LIKE ?', location]) if location.present?
    lodgings = lodgings.where(['pets_accepted LIKE ?', pets_accepted]) if pets_accepted.present?
    lodgings = lodgings.where(['parking_lot LIKE ?', parking_lot]) if parking_lot.present?
    lodgings = lodgings.where(['breakfast_included LIKE ?', breakfast_included]) if breakfast_included.present?
    lodgings = lodgings.where(['single_bed == ?', single_bed]) if single_bed.present?
    lodgings = lodgings.where(['double_bed == ?', double_bed]) if double_bed.present?
    lodgings = lodgings.where(['rooms == ?', rooms]) if rooms.present?
    lodgings = lodgings.where(['bathrooms == ?', bathrooms]) if bathrooms.present?
    lodgings = lodgings.where(['jacuzzi LIKE ?', jacuzzi]) if jacuzzi.present?
    lodgings = lodgings.where(['gym LIKE ?', gym]) if gym.present?
    lodgings = lodgings.where(['smoke_free LIKE ?', smoke_free]) if smoke_free.present?

    return lodgings
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  # GET /searches/new
  def new
    @search = Search.new
  end

  # POST /searches or /searches.json
  def create
    @search = Search.create(search_params)
    redirect_to @search, notice: "This are the results of your search."
  end

  # GET /searches/1 or /searches/1.json
  def show
    @search = Search.find(params[:id])
  end

  private

  # Only allow a list of trusted parameters through.
  def search_params
    params.require(:search).permit(:keywords, :check_in, :check_out, :daily_fee_min,
                                   :daily_fee_max, :location, :pets_accepted,
                                   :parking_lot, :breakfast_included, :single_bed,
                                   :double_bed, :rooms, :bathrooms, :jacuzzi, :gym,
                                   :smoke_free)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with(model: search) do |form| %>
  <form>
    <div class="row">
      <div class="col-sm-4 col-md-4 py-4">
        <div class="mb-2">
          <%= form.label :keywords, class: "form-label" %>
          <%= form.text_field :keywords, class: "form-control" %>
        </div>

        <div class="mb-2" style="margin-top: 1rem">
          <p> <%= form.label :check_in, "Check In", class: "form-label"   %>:   <%= form.date_select :check_in, size:10, class: "form-control" %></p>
          <p> <%= form.label :Check_out, "Check Out", class: "form-label"   %>: <%= form.date_select :check_out, size:10, class: "form-control" %></p>
          <p><%= form.label :location, class: "form-label" %> <%= form.text_field :location, class: "form-control" %></p>
        </div>
      </div>
      <div class="col-sm-4 col-md-2 py-4">
        <div class="mb-2">
          <p> <%= form.label :daily_fee_min, "Daily fee Min", class: "form-label"   %>  <%= form.text_field :daily_fee_min, size:10, class: "form-control" %></p>
          <p> <%= form.label :daily_fee_max, "Daily fee Max" , class: "form-label"  %>  <%= form.text_field :daily_fee_max, size:10, class: "form-control" %></p>
        </div>

        <div class="mb-2">
          <%= form.label :single_bed, class: "form-label" %>
          <%= form.number_field :single_bed, class: "form-control" %>
        </div>

      </div>
      <div class="col-sm-4 col-md-2 py-4">

        <div class="mb-2">
          <%= form.label :double_bed, class: "form-label" %>
          <%= form.number_field :double_bed, class: "form-control" %>
        </div>

        <div class="mb-2" style="margin-top: 1rem">
          <%= form.label :rooms, class: "form-label" %>
          <%= form.number_field :rooms, class: "form-control" %>
        </div>

        <div class="mb-2" style="margin-top: 1rem">
          <%= form.label :bathrooms, class: "form-label" %>
          <%= form.number_field :bathrooms, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4 col-md-2 py-4" style="margin-top: 2rem">
        <div class="mb-3 form-check">
          <%= form.label :pets_accepted, class: "form-check-label" %>
          <%= form.check_box :pets_accepted, class: "form-check-input" %>
        </div>

        <div class="mb-3 form-check">
          <%= form.label :parking_lot, class: "form-check-label" %>
          <%= form.check_box :parking_lot , class: "form-check-input"%>
        </div>

        <div class="mb-3 form-check">
          <%= form.label :breakfast_included, class: "form-check-label" %>
          <%= form.check_box :breakfast_included, class: "form-check-input" %>
        </div>

        <div class="mb-3 form-check">
          <%= form.label :jacuzzi , class: "form-check-label"%>
          <%= form.check_box :jacuzzi , class: "form-check-input"%>
        </div>


      </div>
      <div class="col-sm-4 col-md-2 py-4" style="margin-top: 2rem">
        <div class="mb-3 form-check">
          <%= form.label :gym, class: "form-check-label" %>
          <%= form.check_box :gym, class: "form-check-input" %>
        </div>
        <div class="mb-3 form-check">
          <%= form.label :smoke_free, class: "form-check-label" %>
          <%= form.check_box :smoke_free, class: "form-check-input" %>
        </div>

        <button type="submit" class="btn btn-lg btn-block">SEARCH</button>
      </div>
    </div>
  </form>
<% end %>

app/views/searches/_searchB.html.erb
<%= form_with(model: search) do |form| %>
  <form>
    <div class="row">
      <div class="col-sm-4 col-md-4 py-4">
        <div class="mb-2 text-white">
          <%= form.label :keywords, class: "form-label" %>
          <%= form.text_field :keywords, class: "form-control" %>
        </div>

        <div class="mb-2 text-white" style="margin-top: 1rem">
          <p> <%= form.label :check_in, "Check In", class: "form-label"   %>:   <%= form.date_select :check_in, size:10, class: "form-control" %></p>
          <p> <%= form.label :Check_out, "Check Out", class: "form-label"   %>: <%= form.date_select :check_out, size:10, class: "form-control" %></p>
          <p><%= form.label :location, class: "form-label" %> <%= form.text_field :location, class: "form-control" %></p>
        </div>
      </div>
      <div class="col-sm-4 col-md-2 py-4">
        <div class="mb-2 text-white">
          <p> <%= form.label :daily_fee_min, "Daily fee Min", class: "form-label"   %>  <%= form.text_field :daily_fee_min, size:10, class: "form-control" %></p>
          <p> <%= form.label :daily_fee_max, "Daily fee Max" , class: "form-label"  %>  <%= form.text_field :daily_fee_max, size:10, class: "form-control" %></p>
        </div>

        <div class="mb-2 text-white">
          <%= form.label :single_bed, class: "form-label" %>
          <%= form.number_field :single_bed, class: "form-control" %>
        </div>

      </div>
      <div class="col-sm-4 col-md-2 py-4">

        <div class="mb-2 text-white">
          <%= form.label :double_bed, class: "form-label" %>
          <%= form.number_field :double_bed, class: "form-control" %>
        </div>

        <div class="mb-2 text-white" style="margin-top: 1rem">
          <%= form.label :rooms, class: "form-label" %>
          <%= form.number_field :rooms, class: "form-control" %>
        </div>

        <div class="mb-2 text-white" style="margin-top: 1rem">
          <%= form.label :bathrooms, class: "form-label" %>
          <%= form.number_field :bathrooms, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4 col-md-2 py-4" style="margin-top: 2rem">
        <div class="mb-3 form-check text-white">
          <%= form.label :pets_accepted, class: "form-check-label" %>
          <%= form.check_box :pets_accepted, class: "form-check-input" %>
        </div>

        <div class="mb-3 form-check text-white">
          <%= form.label :parking_lot, class: "form-check-label" %>
          <%= form.check_box :parking_lot , class: "form-check-input"%>
        </div>

        <div class="mb-3 form-check text-white">
          <%= form.label :breakfast_included, class: "form-check-label" %>
          <%= form.check_box :breakfast_included, class: "form-check-input" %>
        </div>

        <div class="mb-3 form-check text-white">
          <%= form.label :jacuzzi , class: "form-check-label"%>
          <%= form.check_box :jacuzzi , class: "form-check-input"%>
        </div>


      </div>
      <div class="col-sm-4 col-md-2 py-4" style="margin-top: 2rem">
        <div class="mb-3 form-check text-white">
          <%= form.label :gym, class: "form-check-label" %>
          <%= form.check_box :gym, class: "form-check-input" %>
        </div>
        <div class="mb-3 form-check text-white">
          <%= form.label :smoke_free, class: "form-check-label" %>
          <%= form.check_box :smoke_free, class: "form-check-input" %>
        </div>

        <button type="submit" class="btn-light btn-lg btn-block">SEARCH</button>
      </div>
    </div>
  </form>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Searches</h1>

<table>
  <thead>
    <tr>

      <th>Keywords</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Daily fee min</th>
      <th>Daily fee max</th>
      <th>Location</th>
      <th>Pets accepted</th>
      <th>Parking lot</th>
      <th>Breakfast included</th>
      <th>Single bed</th>
      <th>Double bed</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th>Jacuzzi</th>
      <th>Gym</th>
      <th>Smoke free</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.keywords %></td>
        <td><%= search.check_in %></td>
        <td><%= search.check_out %></td>
        <td><%= search.daily_fee_min %></td>
        <td><%= search.daily_fee_max %></td>
        <td><%= search.location %></td>
        <td><%= search.pets_accepted %></td>
        <td><%= search.parking_lot %></td>
        <td><%= search.breakfast_included %></td>
        <td><%= search.single_bed %></td>
        <td><%= search.double_bed %></td>
        <td><%= search.rooms %></td>
        <td><%= search.bathrooms %></td>
        <td><%= search.jacuzzi %></td>
        <td><%= search.gym %></td>
        <td><%= search.smoke_free %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<div style="margin: 3rem">
  <div style="margin: 3rem">
    <h1>Advance Search</h1>
    <span>
      <button type="button" class="btn btn-outline-dark align-content-center float-end" style="margin-right: 5px"><%= link_to 'Back', searches_path %></button>
    </span>
  </div>

  <%= render 'form', search: @search %>

</div>

app/views/searches/show.html.erb
<div style="margin: 3rem">

  <div style="margin: 3rem">
    <p><h1><strong> Lodgings Results </strong></h1>

    <span>
      <button type="button" class="btn btn-outline-dark align-content-center float-end" > <%= link_to 'Back', new_search_path %></button>
    </span>
  </div>

  <table class="table table-dark table-striped table-hover" style="margin-top: 2rem">
    <thead>
    <tr>
      <th scope="col">#id</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @search.search_lodgings.each do |lodging| %>
      <tr id="tabla1">
        <td scope="row"><%= lodging.id %></td>
        <td><%= lodging.name %></td>
        <td><%= lodging.description %></td>
        <td><button type="button" class="btn btn-light"><%= link_to 'Show', lodging%></button></td>
        <td><button type="button" class="btn btn-light"><%= link_to 'Edit', edit_lodging_path(lodging) %></button></td>
        <td><button type="button" class="btn btn-light"><%= link_to 'Destroy', lodging, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>