config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :searches
  resources :review_users
  resources :review_lodgings
  resources :reservations
  resources :reports
  resources :messages
  resources :users
  resources :lodgings

  resources :users do
    resources :lodgings, shallow: true
  end
  resources :users do
    resources :reservations, shallow: true
  end
  resources :users do
    resources :review_users, shallow: true
  end
  resources :users do
    resources :review_lodgings, shallow: true
  end
  resources :users do
    resources :messages, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :lodgings
      end
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lodgings
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

end

app/models/lodging.rb
class Lodging < ApplicationRecord
  belongs_to :user
  has_many :review_lodgings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many_attached :images
  has_many_attached :videos
  validates :name, presence: true
  validates :daily_fee, presence: true
  validates :description, presence: true
  validates :rooms, presence: true
  validates :user_id, presence: true
  validates :location, presence: true
  validates :bathrooms, presence: true


  accepts_nested_attributes_for :review_lodgings, allow_destroy: true
  accepts_nested_attributes_for :reservations, allow_destroy: true

  def thumbnail input
    images[input].variant(resize: '300x300').processed
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/api/v1/lodgings_controller.rb
class API::V1::LodgingsController < APIController
  before_action :set_user, only: [:index, :create, :show, :update, :destroy]
  before_action :set_lodging, only:[:show, :update, :destroy]


  # GET /api/v1/users/1/lodgings
  def index
    @lodgings = Lodging.where(user: @user)
  end

  # GET /api/v1/users/1/lodgings
  def show
  end

  # GET /lodgings/new
  def new
    @lodging = Lodging.new
  end

  # GET /lodgings/1/edit
  def edit
  end

  # POST /lodgings or /lodgings.json
  def create
    @lodging = Lodging.new(lodging_params)
    @lodging.user = @user
    if @lodging.update(lodging_params)
      render :show, status: :ok, location: api_v1_user_lodgings_path(@lodging)
    else
      render json: @lodging.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lodgings/1 or /lodgings/1.json
  def update
    @lodging.user = @user
    if @lodging.update(lodging_params)
      render :show, status: :ok, location: api_v1_user_lodgings_path(@lodging)
    else
      render json: @lodging.errors, status: :unprocessable_entity
    end
  end

  # DELETE /lodgings/1 or /lodgings/1.json
  def destroy
    @user = @lodging.user
    @lodging.destroy
    redirect_to api_v1_user_lodgings_path(@user)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_lodging
    @lodging = Lodging.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

    # Only allow a list of trusted parameters through.
  # Only allow a list of trusted parameters through.
  def lodging_params
    params.fetch(:lodging, {}).
      permit(:id, :name, :availability_from,
             :availability_to,:description, :daily_fee, :location,
             :pets_accepted, :parking_lot, :breakfast_included,
             :single_bed, :double_bed, :rooms, :bathrooms, :jacuzzi,
             :gym, :smoke_free, :user_id,
             { review_lodgings_attributes: [:id, :text, :rating],
               reservations_attributes: [:id, :entry_date, :deparure_date,
                                         :price, :transfer_receipt,
                                         :reserve_expiration]
             })
  end

end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController

  before_action :set_lodging, only: %i[ show edit update destroy ]

  # GET /lodgings or /lodgings.json
  def index
    if params.has_key?(:user_id)
      @user = User.find(params[:user_id])
      @lodgings = Lodging.where(user_id: params[:user_id])
    else
      @lodgings = Lodging.search(params[:search])
    end

  end

  # GET /lodgings/1 or /lodgings/1.json
  def show
  end

  # GET /lodgings/new
  def new
    @lodging = Lodging.new
  end

  # GET /lodgings/1/edit
  def edit
  end

  # POST /lodgings or /lodgings.json
  def create
    @lodging = Lodging.new(lodging_params)

    respond_to do |format|
      if @lodging.save
        format.html { redirect_to @lodging, notice: "Lodging was successfully created." }
        format.json { render :show, status: :created, location: @lodging }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lodgings/1 or /lodgings/1.json
  def update
    respond_to do |format|
      if @lodging.update(lodging_params)
        format.html { redirect_to @lodging, notice: "Lodging was successfully updated." }
        format.json { render :show, status: :ok, location: @lodging }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lodgings/1 or /lodgings/1.json
  def destroy
    @lodging.destroy
    respond_to do |format|
      format.html { redirect_to lodgings_url, notice: "Lodging was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_lodging
    @lodging = Lodging.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def lodging_params
    params.require(:lodging).permit(:user_id, :name, :description,
                                    :daily_fee, :location, :availability_from,
                                    :availability_to, :pets_accepted,
                                    :parking_lot, :breakfast_included,
                                    :single_bed, :double_bed, :rooms,
                                    :bathrooms, :jacuzzi, :gym, :smoke_free,
                                    images: [], videos: [])
  end
end

app/helpers/lodgings_helper.rb
module LodgingsHelper

  def beers_purge_watchlist
    session[:watch_list] = "[]"
  end
end

app/views/lodgings/_form.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", initMap2);
  </script>
<% end %>
<div style="margin: 3rem">
  <%= form_with(model: lodging) do |form| %>
    <% if lodging.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% lodging.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <form>
      <%= form.hidden_field :user_id, class: "form-control", value: current_user.id %>

    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :daily_fee, class: "form-label" %>
      <%= form.text_field :daily_fee, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :location, class: "form-label" %>
      <%= form.text_field :location, class: "form-control" %>
    </div>


    <div class="mb-3">
      <%= form.label :images, class: "form-label" %>
      <%= form.file_field :images, multiple: true, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :videos, class: "form-label" %>
      <%= form.file_field :videos, multiple: true, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :single_bed, class: "form-label" %>
      <%= form.number_field :single_bed, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :double_bed, class: "form-label" %>
      <%= form.number_field :double_bed, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :rooms, class: "form-label" %>
      <%= form.number_field :rooms, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :bathrooms, class: "form-label" %>
      <%= form.number_field :bathrooms, class: "form-control" %>
    </div>
    <div class="mb-3 form-check">
      <%= form.label :pets_accepted, class: "form-check-label" %>
      <%= form.check_box :pets_accepted, class: "form-check-input" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.label :parking_lot,  class: "form-check-label" %>
      <%= form.check_box :parking_lot, class: "form-check-input" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.label :breakfast_included,  class: "form-check-label" %>
      <%= form.check_box :breakfast_included, class: "form-check-input" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.label :jacuzzi,  class: "form-check-label" %>
      <%= form.check_box :jacuzzi, class: "form-check-input" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.label :gym,  class: "form-check-label" %>
      <%= form.check_box :gym, class: "form-check-input" %>
    </div>

    <div class="mb-3 form-check">
      <%= form.label :smoke_free,  class: "form-check-label" %>
      <%= form.check_box :smoke_free, class: "form-check-input" %>
    </div>
      <div class="field">
        <%= form.label :latitude %>
        <%= form.text_field :latitude %>
      </div>

      <div class="field">
        <%= form.label :longitude %>
        <%= form.text_field :longitude %>
      </div>
      <p>
      <div id="map2"></div>
      </p>

      <button type="submit" class="btn btn-outline-dark btn-lg btn-block">Submit</button>

    </form>
  <% end %>



</div>

app/views/lodgings/edit.html.erb
<div style="margin: 3rem">
  <div style="margin: 3rem">
    <h1>Editing Lodging</h1>
    <span>
      <%= link_to 'Show', @lodging, class: "btn btn-outline-dark align-content-center float-end"%>
      <%= link_to 'Back', lodgings_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>
    </span>
  </div>


  <%= render 'form', lodging: @lodging %>


</div>

app/views/lodgings/index.html.erb
<div style="margin: 3rem">
 <div style="margin-left: 3rem">
   <h1>Lodgings</h1>

   <%= form_tag lodgings_path, :method => 'get' do %>
     <%= text_field_tag :search, params[:search] %>
     <%= submit_tag "Search" %>
   <%end %>

   <%= link_to "Advance Search", new_search_path%>
 </div>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @lodgings.each do |lodging| %>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">No Image Aviable</text></svg>
              <div class="card-body">
                <a class="card-title"><%=lodging.name %></a>
                <p class="card-text" type="text-overflow: ellipsis" ><%=lodging.description %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to 'View', lodging, class: "btn btn-sm btn-outline-secondary" %>
                    <%if can? :manage, :lodging or lodging.user_id == current_user.id%>
                      <%= link_to 'Edit', edit_lodging_path(lodging), class: "btn btn-sm btn-outline-secondary" %>
                      <%= link_to 'Delete', lodging, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" %>

                    <%end%>
                  </div>
                  <small class="text-muted"> $ <%=lodging.daily_fee %> p/night</small>
                </div>
              </div>
            </div>
          </div>

      <% end %>
      </div>

    </div>
  </div>

  <br>
  <div class="d-grid gap-2">
    <%= link_to 'New Lodging', new_lodging_path, class: "btn btn-outline-dark btn-lg btn-block"%>

  </div>



</div>

app/views/lodgings/new.html.erb
<div style="margin: 3rem">
  <div style="margin: 3rem">
    <h1>New Lodging</h1>

    <span>
      <%= link_to 'Back', user_lodgings_path(current_user), class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>

    </span>
  </div>


<%= render 'form', lodging: @lodging %>

</div>

app/views/lodgings/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", function(){
          initMap(<%=@lodging.latitude%>, <%=@lodging.longitude%>)
      });
  </script>
<% end %>
<div style="margin: 3rem">

  <div style="margin: 3rem">
    <p><h3><strong><%= @lodging.name %></strong></h3>

    <span>
      <%if can? :manage, :lodging %>
      <%= link_to 'Edit', edit_lodging_path(@lodging), class: "btn btn-outline-dark align-content-center float-end"%>
      <%end %>
      <%unless !user_signed_in?%>
      <%= link_to 'Back', lodgings_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>
      <%= link_to 'Write Review', new_review_lodging_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 15px"%>
      <%= link_to 'Reserve', new_user_reservation_path(current_user), class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 15px"%>
      <%= link_to 'Contact Guest', new_user_message_path(current_user), class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 15px"%>
      <%else %>
       <%= link_to 'Back', lodgings_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 5px"%>
        <%= link_to 'Write Review', new_review_lodging_path, class: "btn btn-outline-dark align-content-center float-end", style: "margin-right: 15px"%>
      <%end %>
     </span>
  </div>
  <p>
    <strong>Description:</strong>
    <%= @lodging.description %>
  </p>

  <p>
    <strong>Daily fee:</strong>
    <%= @lodging.daily_fee %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @lodging.location %>
  </p>

  <p>
    <strong>Images:</strong>
    <% (0...@lodging.images.count).each do |image| %>
        <%= image_tag(@lodging.thumbnail(image)) %>
    <% end %>

  </p>

  <p>
    <strong>Video:</strong>
    <% (0...@lodging.videos.count).each do |video| %>
      <%= video_tag(url_for(@lodging.videos[video]), controls:'') %>
    <% end %>
  </p>

  <p>
    <strong>Pets accepted:</strong>
    <%= @lodging.pets_accepted %>
  </p>

  <p>
    <strong>Parking lot:</strong>
    <%= @lodging.parking_lot %>
  </p>

  <p>
    <strong>Breakfast included:</strong>
    <%= @lodging.breakfast_included %>
  </p>

  <p>
    <strong>Single bed:</strong>
    <%= @lodging.single_bed %>
  </p>

  <p>
    <strong>Double bed:</strong>
    <%= @lodging.double_bed %>
  </p>

  <p>
    <strong>Rooms:</strong>
    <%= @lodging.rooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= @lodging.bathrooms %>
  </p>

  <p>
    <strong>Jacuzzi:</strong>
    <%= @lodging.jacuzzi %>
  </p>

  <p>
    <strong>Gym:</strong>
    <%= @lodging.gym %>
  </p>

  <p>
    <strong>Smoke free:</strong>
    <%= @lodging.smoke_free %>
  </p>
  <p>
    <strong>Latitude:</strong>
    <%= @lodging.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @lodging.longitude %>
  </p>

  <p>
  <div id="map"></div>
  </p>


</div>