config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :searches
  resources :review_users
  resources :review_lodgings
  resources :reservations
  resources :reports
  resources :messages
  resources :users
  resources :lodgings

  resources :users do
    resources :lodgings, shallow: true
  end
  resources :users do
    resources :reservations, shallow: true
  end
  resources :users do
    resources :review_users, shallow: true
  end
  resources :users do
    resources :review_lodgings, shallow: true
  end
  resources :users do
    resources :messages, shallow: true
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :lodgings
      end
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :lodgings
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lodging.rb
class Lodging < ApplicationRecord
  belongs_to :user
  has_many :review_lodgings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many_attached :images
  has_many_attached :videos
  validates :name, presence: true
  validates :daily_fee, presence: true
  validates :description, presence: true
  validates :rooms, presence: true
  validates :user_id, presence: true
  validates :location, presence: true
  validates :bathrooms, presence: true


  accepts_nested_attributes_for :review_lodgings, allow_destroy: true
  accepts_nested_attributes_for :reservations, allow_destroy: true

  def thumbnail input
    images[input].variant(resize: '300x300').processed
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messageSender, class_name: 'User', foreign_key: 'messageSender_id'
  belongs_to :messageReceiver, class_name: 'User', foreign_key: 'messageReceiver_id'
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reportSender, class_name: 'User', foreign_key: 'reportSender_id'
  belongs_to :reportReceiver, class_name: 'User', foreign_key: 'reportReceiver_id'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :lodging
  belongs_to :user
end

app/models/review_lodging.rb
class ReviewLodging < ApplicationRecord
  belongs_to :lodging
  belongs_to :user
end

app/models/review_user.rb
class ReviewUser < ApplicationRecord
  belongs_to :received, class_name: 'User', foreign_key: 'received_id'
  belongs_to :made, class_name: 'User', foreign_key: 'made_id'
end

app/models/search.rb
class Search < ApplicationRecord

  def search_lodgings

    lodgings = Lodging.all
    lodgings = lodgings.where(['name LIKE ?', "%#{keywords}"]) if keywords.present?
    lodgings = lodgings.where(['availability_from <= ?', check_in]) if check_in.present?
    lodgings = lodgings.where(['availability_to >= ?', check_out]) if check_out.present?
    lodgings = lodgings.where(['daily_fee >= ?', daily_fee_min]) if daily_fee_min.present?
    lodgings = lodgings.where(['daily_fee <= ?', daily_fee_max]) if daily_fee_max.present?
    lodgings = lodgings.where(['location LIKE ?', location]) if location.present?
    lodgings = lodgings.where(['pets_accepted LIKE ?', pets_accepted]) if pets_accepted.present?
    lodgings = lodgings.where(['parking_lot LIKE ?', parking_lot]) if parking_lot.present?
    lodgings = lodgings.where(['breakfast_included LIKE ?', breakfast_included]) if breakfast_included.present?
    lodgings = lodgings.where(['single_bed == ?', single_bed]) if single_bed.present?
    lodgings = lodgings.where(['double_bed == ?', double_bed]) if double_bed.present?
    lodgings = lodgings.where(['rooms == ?', rooms]) if rooms.present?
    lodgings = lodgings.where(['bathrooms == ?', bathrooms]) if bathrooms.present?
    lodgings = lodgings.where(['jacuzzi LIKE ?', jacuzzi]) if jacuzzi.present?
    lodgings = lodgings.where(['gym LIKE ?', gym]) if gym.present?
    lodgings = lodgings.where(['smoke_free LIKE ?', smoke_free]) if smoke_free.present?

    return lodgings
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  validates :email, email: true, uniqueness: true, presence: true
  has_many :lodgings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :review_users_received, class_name: 'ReviewUser', foreign_key: 'received_id' , dependent: :destroy
  has_many :review_users_made, class_name: 'ReviewUser', foreign_key: 'made_id' , dependent: :destroy
  has_many :inbox_as_messageSender, class_name: 'Message', foreign_key: 'messageSender_id' , dependent: :destroy
  has_many :inbox_as_messageReceiver, class_name: 'Message', foreign_key: 'messageReceiver_id' , dependent: :destroy
  has_many :sended_reports, class_name: 'Report', foreign_key: 'reportSender_id' , dependent: :destroy
  has_many :received_reports, class_name: 'Report', foreign_key: 'reportReceiver_id' , dependent: :destroy


  accepts_nested_attributes_for :lodgings, allow_destroy: true
  accepts_nested_attributes_for :reservations, allow_destroy: true
  accepts_nested_attributes_for :review_users_received, allow_destroy: true
  accepts_nested_attributes_for :review_users_made, allow_destroy: true
  accepts_nested_attributes_for :inbox_as_messageSender, allow_destroy: true
  accepts_nested_attributes_for :inbox_as_messageReceiver, allow_destroy: true
  accepts_nested_attributes_for :sended_reports, allow_destroy: true
  accepts_nested_attributes_for :received_reports, allow_destroy: true


end

app/controllers/api_controller.rb
class APIController < ActionController::API
end

app/helpers/api_helper.rb
module APIHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lodgings_helper.rb
module LodgingsHelper

  def beers_purge_watchlist
    session[:watch_list] = "[]"
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iSpot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBj67DY5XGEwI-KvNxZcEREuZ4oVdrLR2g' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>
  <body>
  <meta name='turbolinks-visit-control' content='reload'>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="people-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
      </symbol>
    </svg>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
      <symbol id="bi bi-search" viewBox="0 0 16 16">
      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </symbol>
    </svg>

    <header>
      <div class="fixed-top">
        <div class="collapse bg-dark" id="navbarHeader" style="background-color: #403d3d;">
          <div class="container">

            <%= render 'searches/searchB', search: @search %>

          </div>
        </div>
        <div class="navbar navbar-dark shadow-sm" style="background-color: #323232;">
          <div class="container">
            <a href="/" >
              <%=image_tag("logoISPOT.png", srcset: { "logoISPOT.png" => "2.5x" }) %>
            </a>
            <ul class="nav me-auto mb-2 mb-lg-0" style="padding-left: 20px">
              <%= link_to 'Home', root_path, class: "nav-link px-2 text-white"%>
              <%= link_to 'Lodgings', lodgings_path, class: "nav-link px-2 text-white"%>
              <%= link_to 'Users', users_path, class: "nav-link px-2 text-white"%>
            </ul>
            <a class="navbar-toggler btn-close-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <svg class="bi d-block mx-auto mb-1" width="40" height="40"><use xlink:href="#bi bi-search"/></svg>
            </a>
            <a class="navbar-toggler dropdown-toggle-split btn-close-white" type="button"  id="navbarDropdownMenuUser" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <svg class="bi d-block mx-auto mb-1" width="40" height="40"><use xlink:href="#people-circle"/></svg>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuUser" >
              <%unless !user_signed_in?%>
                &nbsp;&nbsp;&nbsp; <b>Welcome, <i><%=current_user.first_name%></i></b>
                  <%= link_to 'Profile', edit_user_registration_path(current_user), class: "dropdown-item"%>
                  <%= link_to 'Messages', user_messages_path(current_user), class: "dropdown-item"%>
                  <%= link_to 'My Lodgings', user_lodgings_path(current_user), class: "dropdown-item"%>
                  <%= link_to 'My Reservations', user_reservations_path(current_user), class: "dropdown-item"%>
                  <%= link_to 'My Lodgings Reviews', user_review_lodgings_path(current_user), class: "dropdown-item"%>
                  <%= link_to 'My Users Reviews', user_review_users_path(current_user), class: "dropdown-item"%>
                  <hr class="dropdown-divider">
                  <%=link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>

                <%else%>
                  <%=link_to "Sign in", new_user_session_path, class: "dropdown-item" %>
                  <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, method: :post %>
                <hr class="dropdown-divider">
                  <%=link_to "Register", new_user_registration_path, class: "dropdown-item" %>

            <%end%>
            </ul>
          </div>
        </div>
      </div>

    </header>

    <main>
        <% unless flash[:notice].nil? %>
          <div class="row mb-2" style="margin: 3rem">
            <div class="col-6">
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                <%=flash[:notice]%>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            </div>
            <div class="col">
            </div>
          </div>
        <% end %>
        <%= yield %>
    </main>
    <!-- FOOTER -->

    <footer class="container">
      <hr class="featurette-divider" style="margin-bottom: 1rem">
      <div class="container bg-dark text-white">
        <p style="padding-left: 1rem" >&copy; 2021 iSpot, Inc.&nbsp; &middot; &nbsp;<a class="text-white" href="https://www.termsofservicegenerator.net/live.php?token=RTNa8moVQwt5Sh8hBZ397CFyerJgUBoR" style="text-decoration: none">Terms of Service</a> &nbsp; &middot; &nbsp;
          <a class="text-white" style="text-decoration: none" href="https://www.termsofusegenerator.net/live.php?token=BSaxgYtBWTnZtrkCUg0QpbDwvEINGB1a">Terms of Use</a>&nbsp; &middot; &nbsp;<a class="text-white" style="text-decoration: none" href="/reports">Reports</a><i id = "icn_instagram"class="bi bi-instagram" href="/"></i>   &nbsp;
          <i class="bi bi-facebook" href="/"></i>  &nbsp;
          <i class="bi bi-twitter" href="/"></i>
        </p>
      </div>

    </footer>
  </body>
</html>

app/views/pages/_search.html.erb
<%= form_with(model: search) do |form| %>
  <form>
    <div class="row">
      <div class="col-sm-4 col-md-4 py-4">
        <div class="mb-2 text-white">
          <%= form.label :keywords, class: "form-label" %>
          <%= form.text_field :keywords, class: "form-control" %>
        </div>

        <div class="mb-2 text-white" style="margin-top: 1rem">
          <p> <%= form.label :check_in, "Check In", class: "form-label"   %>:   <%= form.date_select :check_in, size:10, class: "form-control" %></p>
          <p> <%= form.label :Check_out, "Check Out", class: "form-label"   %>: <%= form.date_select :check_out, size:10, class: "form-control" %></p>
          <p><%= form.label :location, class: "form-label" %> <%= form.text_field :location, class: "form-control" %></p>
        </div>
      </div>
      <div class="col-sm-4 col-md-2 py-4">
        <div class="mb-2 text-white">
          <p> <%= form.label :daily_fee_min, "Daily fee Min", class: "form-label"   %>  <%= form.text_field :daily_fee_min, size:10, class: "form-control" %></p>
          <p> <%= form.label :daily_fee_max, "Daily fee Max" , class: "form-label"  %>  <%= form.text_field :daily_fee_max, size:10, class: "form-control" %></p>
        </div>

        <div class="mb-2 text-white">
          <%= form.label :single_bed, class: "form-label" %>
          <%= form.number_field :single_bed, class: "form-control" %>
        </div>

      </div>
      <div class="col-sm-4 col-md-2 py-4">

        <div class="mb-2 text-white">
          <%= form.label :double_bed, class: "form-label" %>
          <%= form.number_field :double_bed, class: "form-control" %>
        </div>

        <div class="mb-2 text-white" style="margin-top: 1rem">
          <%= form.label :rooms, class: "form-label" %>
          <%= form.number_field :rooms, class: "form-control" %>
        </div>

        <div class="mb-2 text-white" style="margin-top: 1rem">
          <%= form.label :bathrooms, class: "form-label" %>
          <%= form.number_field :bathrooms, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4 col-md-2 py-4" style="margin-top: 2rem">
        <div class="mb-3 form-check text-white">
          <%= form.label :pets_accepted, class: "form-check-label" %>
          <%= form.check_box :pets_accepted, class: "form-check-input" %>
        </div>

        <div class="mb-3 form-check text-white">
          <%= form.label :parking_lot, class: "form-check-label" %>
          <%= form.check_box :parking_lot , class: "form-check-input"%>
        </div>

        <div class="mb-3 form-check text-white">
          <%= form.label :breakfast_included, class: "form-check-label" %>
          <%= form.check_box :breakfast_included, class: "form-check-input" %>
        </div>

        <div class="mb-3 form-check text-white">
          <%= form.label :jacuzzi , class: "form-check-label"%>
          <%= form.check_box :jacuzzi , class: "form-check-input"%>
        </div>


      </div>
      <div class="col-sm-4 col-md-2 py-4" style="margin-top: 2rem">
        <div class="mb-3 form-check text-white">
          <%= form.label :gym, class: "form-check-label" %>
          <%= form.check_box :gym, class: "form-check-input" %>
        </div>
        <div class="mb-3 form-check text-white">
          <%= form.label :smoke_free, class: "form-check-label" %>
          <%= form.check_box :smoke_free, class: "form-check-input" %>
        </div>
        <button  class="btn btn-outline-white btn-lg btn-block" >SEARCH</button>
      </div>
    </div>
  </form>
<% end %>

app/views/pages/home.html.erb
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-auto" width=100%" height="100%" src="https://fondosmil.com/fondo/24521.jpg" aria-hidden="true" >
      <div class="container">
        <div class="carousel-caption text-start">
          <h1>Find your perfect iSpot.</h1>
          <p> An experience that will change you. </p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-auto" width="100%" height="100%" src="https://a0.muscache.com/im/pictures/c359315f-6434-41b0-b301-2288e4e11d15.jpg?im_w=1200" aria-hidden="true" >
      <div class="container">
        <div class="carousel-caption">
          <h1> Your dreams come true.</h1>
          <p> Share it, with the ones you love the most.</p>
          <p><a class="btn btn-lg btn-primary" href="/lodgings">Make it True</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-auto" width="100%" height="100%" src="https://a0.muscache.com/im/pictures/d1dc10ef-f118-4a94-ab15-98c0ba219427.jpg?im_w=720" aria-hidden="true" >
      <div class="container">
        <div class="carousel-caption text-end">
          <h1>Or take a business trip.</h1>
          <p>With the best office in the world.</p>
          <p><a class="btn btn-lg btn-primary" href="/lodgings/<%= @home_reviews[1].lodging_id%>">Take a look</a></p>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<!-- Tops reviews
================================================== -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="https://pymstatic.com/44253/conversions/xavier-molina-medium.jpg" role="img" aria-label="Placeholder: 140x140">
      <h2><%= @home_reviews[0].user.first_name%> <%= @home_reviews[0].rating%></h2>
      <p><%= @home_reviews[0].text%></p>
      <p><a class="btn btn-secondary" href="/review_lodgings/<%= @home_reviews[0].lodging_id%>">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="https://www.webconsultas.com/sites/default/files/styles/wc_adaptive_image__small/public/articulos/perfil-resilencia.jpg" role="img" aria-label="Placeholder: 140x140">

      <h2><%= @home_reviews[1].user.first_name%> <%= @home_reviews[1].rating%></h2>
      <p><%= @home_reviews[1].text%></p>
      <p><a class="btn btn-secondary" href="/review_lodgings/<%= @home_reviews[1].lodging_id%>">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="https://psicologiayautoayuda.com/wp-content/uploads/2016/05/personas-toxicas.jpg" role="img" aria-label="Placeholder: 140x140">

      <h2><%= @home_reviews[2].user.first_name%>  <%= @home_reviews[2].rating%></h2>
      <p><%= @home_reviews[2].text%></p>
      <p><a class="btn btn-secondary" href="/review_lodgings/<%= @home_reviews[2].lodging_id%>">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->


  <!-- LODGINGS -->

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading"><%= @home_lodgings[0].name%> <span class="text-muted">It’ll blow your mind.</span></h2>
      <p class="lead"><%= @home_lodgings[0].description%></p>
    </div>
    <div class="col-md-5">
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://news.airbnb.com/wp-content/uploads/sites/4/2019/06/PJM020719Q202_Luxe_WanakaNZ_LivingRoom_0264-LightOn_R1.jpg?fit=2500%2C1666" role="img" aria-label="Placeholder: 500x500" >

    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 order-md-2">
      <h2 class="featurette-heading"><%= @home_lodgings[1].name%>  <span class="text-muted">See for yourself.</span></h2>
      <p class="lead"><%= @home_lodgings[1].description%> </p>
    </div>
    <div class="col-md-5 order-md-1">
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://a0.muscache.com/im/pictures/393a0a05-1b90-4e01-980e-30b7499e85d7.jpg?im_w=720" role="img" aria-label="Placeholder: 500x500" >
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading"><%= @home_lodgings[2].name%>  <span class="text-muted">Checkmate.</span></h2>
      <p class="lead"><%= @home_lodgings[2].description%> </p>
    </div>
    <div class="col-md-5">
      <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://news.airbnb.com/wp-content/uploads/sites/4/2020/05/Airbnb-Beachfront-Greece.jpg?fit=2400%2C1600" role="img" aria-label="Placeholder: 500x500" >
    </div>
  </div>
  <!-- /END THE FEATURETTES -->
</div><!-- /.container -->